server:
  port: 81
#    connection-timeout: 30000
#    context-path:
logging:
  level:
    com.x.*: debug
  #path: C\:\\Users\\zwj\\Desktop
  path: /data/logs/x
  file: x.log
  config: classpath:logback-spring.xml







