server:
                  port: 82
                  servlet:
                    context-path: /console
resources:
    static-locations: classpath:/resources/, classpath:/static/ ,classpath:/templates/

spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false





