server:
                  port: 82
                  servlet:
                    context-path: /console
resources:
    static-locations: classpath:/resources/, classpath:/static/ ,classpath:/templates/

spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false

  servlet:
    multipart:
      enabled: false
      max-file-size: 20MB
      max-request-size: 100MB
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true



